describe('App refresh', () => {
    beforeEach(() => {
        cy.visit('localhost:3000')
    })

    const orderLink = () => cy.get(`button[id='order-pizza']`)
    const orderButton = () => cy.get(`button[id='order-button']`)
    const nameInput = () => cy.get('input[name=orderName]')
    const sizeOption = () => cy.get(`select[name=size]`)
    const pepperoni = () => cy.get('input[name=pepperoni]')
    const mushrooms = () => cy.get('input[name=mushrooms]')
    const sausage = () => cy.get('input[name=sausage]')
    const pineapple = () => cy.get('input[name=pineapple]')
    const special = () => cy.get('input[name=special]')


    it('Can navigate to order page and type', () => {
        orderLink()
            .should('exist')
            .click()
        nameInput()
            .should('exist')
            .type('John Doe')
            .should('have.value', 'John Doe')
        special()
            .should('exist')
            .type('extra cheese')
            .should('have.value', 'extra cheese')
    })


    it('Can select multiple toppings', () => {
        orderLink()
            .should('exist')
            .click()
        pepperoni()
            .should('exist')
            .click()
            .should('be.checked')
        mushrooms()
            .should('exist')
            .click()
            .should('be.checked')
    })

    it('Can submit the form', () => {
        orderLink()
            .should('exist')
            .click()
        nameInput()
            .should('exist')
            .type('John Doe')
            .should('have.value', 'John Doe')
        special()
            .should('exist')
            .type('extra cheese')
            .should('have.value', 'extra cheese')
        sizeOption()
            .should('exist')
            .select('Super Size')
        pepperoni()
            .should('exist')
            .click()
            .should('be.checked')
        mushrooms()
            .should('exist')
            .click()
            .should('be.checked')
        sausage()
            .should('exist')
            .click()
            .should('be.checked')
        pineapple()
            .should('exist')
            .click()
            .should('be.checked')
        orderButton()
            .should('exist')
            .click()
        nameInput()
            .should('have.value', '')
        special()
            .should('have.value', '')
    })
})